#version 450

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(set = 0, binding = 0, rgba8) uniform writeonly image2D outputImage;

struct Ray
{
    vec3 origin;
    vec3 direction;
};

vec3 rayAt(Ray ray, float t)
{
    return ray.origin + (t * ray.direction);
}

void writeColor()
{
    imageStore(outputImage, ivec2(gl_GlobalInvocationID.xy), vec4(gl_GlobalInvocationID.x / 2560.0, gl_GlobalInvocationID.y / 1440.0, 1.0, 1.0));
}

void main(void)
{
    writeColor();
}